import 'sport.dart';

enum MatchCategory {
  national,
  league,
  international
}

class Match {
  final String id;
  final String team1;
  final String team2;
  final DateTime dateTime;
  final String venue;
  final SportType sportType;
  final MatchCategory category;
  final String location;
  final Map<String, double> ticketPrices;
  final String imagePath;
  final bool isLive;
  bool hasReminder;
  final bool isFeatured;

  Match({
    required this.id,
    required this.team1,
    required this.team2,
    required this.dateTime,
    required this.venue,
    required this.sportType,
    required this.category,
    required this.location,
    required this.ticketPrices,
    required this.imagePath,
    this.isLive = false,
    this.hasReminder = false,
    this.isFeatured = false,
  });

  String get matchTitle => '$team1 vs $team2';

  String get categoryName {
    switch (category) {
      case MatchCategory.national:
        return 'National';
      case MatchCategory.league:
        return 'League';
      case MatchCategory.international:
        return 'International';
    }
  }

  get awayTeam => null;

  get date => null;

  get homeTeam => null;
}

// Sample matches data
List<Match> generateSampleMatches() {
  final now = DateTime.now();

  return [
    // CRICKET MATCHES
    Match(
      id: 'c1',
      team1: 'Mumbai Indians',
      team2: 'Chennai Super Kings',
      dateTime: now.add(const Duration(days: 2, hours: 3, minutes: 30)),
      venue: 'Wankhede Stadium, Mumbai',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'Maharashtra',
      ticketPrices: {
        'VIP': 5000.0,
        'Premium': 3000.0,
        'Regular': 1500.0,
      },
      imagePath: 'assets/images/mi_vs_csk.jpg',
      isLive: false,
    ),
    Match(
      id: 'c2',
      team1: 'India',
      team2: 'Australia',
      dateTime: now.add(const Duration(days: 5, hours: 2, minutes: 30)),
      venue: 'M. Chinnaswamy Stadium, Bengaluru',
      sportType: SportType.cricket,
      category: MatchCategory.international,
      location: 'Karnataka',
      ticketPrices: {
        'VIP': 8000.0,
        'Premium': 5000.0,
        'Regular': 2500.0,
      },
      imagePath: 'assets/images/ind-vs-eng-h2h-1200-1738047353.jpg',
      isLive: false,
    ),
    Match(
      id: 'c3',
      team1: 'Royal Challengers Bangalore',
      team2: 'Kolkata Knight Riders',
      dateTime: now.add(const Duration(hours: 4)),
      venue: 'M. Chinnaswamy Stadium, Bengaluru',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'Karnataka',
      ticketPrices: {
        'VIP': 4500.0,
        'Premium': 2800.0,
        'Regular': 1400.0,
      },
      imagePath: 'assets/images/rcb_vs_kkr.jpg',
      isLive: true,
    ),
    Match(
      id: 'c4',
      team1: 'Delhi Capitals',
      team2: 'Rajasthan Royals',
      dateTime: now.add(const Duration(days: 3, hours: 3, minutes: 30)),
      venue: 'Arun Jaitley Stadium, Delhi',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 4800.0,
        'Premium': 3200.0,
        'Regular': 1600.0,
      },
      imagePath: 'assets/images/dc_vs_rr.jpg',
      isLive: false,
    ),
    Match(
      id: 'c5',
      team1: 'India',
      team2: 'England',
      dateTime: now.add(const Duration(days: 10, hours: 2)),
      venue: 'Eden Gardens, Kolkata',
      sportType: SportType.cricket,
      category: MatchCategory.international,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 7500.0,
        'Premium': 4500.0,
        'Regular': 2200.0,
      },
      imagePath: 'assets/images/ind-vs-eng-h2h-1200-1738047353.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'c6',
      team1: 'Punjab Kings',
      team2: 'Gujarat Titans',
      dateTime: now.add(const Duration(days: 6, hours: 3, minutes: 30)),
      venue: 'Punjab Cricket Association Stadium, Mohali',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'Punjab',
      ticketPrices: {
        'VIP': 4200.0,
        'Premium': 2600.0,
        'Regular': 1300.0,
      },
      imagePath: 'assets/images/pbks_vs_gt.jpg',
      isLive: false,
    ),
    Match(
      id: 'c7',
      team1: 'Sunrisers Hyderabad',
      team2: 'Lucknow Super Giants',
      dateTime: now.add(const Duration(days: 4, hours: 3, minutes: 30)),
      venue: 'Rajiv Gandhi International Stadium, Hyderabad',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'Telangana',
      ticketPrices: {
        'VIP': 4500.0,
        'Premium': 2800.0,
        'Regular': 1400.0,
      },
      imagePath: 'assets/images/srh_vs_lsg.jpg',
      isLive: false,
    ),
    // New Cricket Match in West Bengal
    Match(
      id: 'c8',
      team1: 'Bengal Tigers',
      team2: 'Jharkhand Jaguars',
      dateTime: now.add(const Duration(days: 8, hours: 2, minutes: 30)),
      venue: 'Eden Gardens, Kolkata',
      sportType: SportType.cricket,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 3500.0,
        'Premium': 2000.0,
        'Regular': 1000.0,
      },
      imagePath: 'assets/images/bengal_vs_jharkhand.jpg',
      isLive: false,
    ),
    Match(
      id: 'c9',
      team1: 'Kolkata Knight Riders',
      team2: 'Chennai Super Kings',
      dateTime: now.add(const Duration(days: 12, hours: 3, minutes: 30)),
      venue: 'Eden Gardens, Kolkata',
      sportType: SportType.cricket,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 5500.0,
        'Premium': 3500.0,
        'Regular': 1800.0,
      },
      imagePath: 'assets/images/kkr_vs_csk.jpg',
      isLive: false,
      isFeatured: true,
    ),
    
    // FOOTBALL MATCHES
    Match(
      id: 'f1',
      team1: 'Bengaluru FC',
      team2: 'Kerala Blasters',
      dateTime: now.add(const Duration(days: 1, hours: 6)),
      venue: 'Sree Kanteerava Stadium, Bengaluru',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'Karnataka',
      ticketPrices: {
        'VIP': 3000.0,
        'Premium': 2000.0,
        'Regular': 1000.0,
      },
      imagePath: 'assets/images/bfc_vs_kb.jpg',
      isLive: false,
    ),
    Match(
      id: 'f2',
      team1: 'Mumbai City FC',
      team2: 'ATK Mohun Bagan',
      dateTime: now.add(const Duration(days: 4, hours: 6, minutes: 30)),
      venue: 'Mumbai Football Arena, Mumbai',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'Maharashtra',
      ticketPrices: {
        'VIP': 3500.0,
        'Premium': 2200.0,
        'Regular': 1100.0,
      },
      imagePath: 'assets/images/mcfc_vs_atkmb.jpg',
      isLive: false,
    ),
    Match(
      id: 'f3',
      team1: 'India',
      team2: 'Nepal',
      dateTime: now.add(const Duration(days: 8, hours: 5)),
      venue: 'Jawaharlal Nehru Stadium, Delhi',
      sportType: SportType.football,
      category: MatchCategory.international,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 2500.0,
        'Premium': 1500.0,
        'Regular': 800.0,
      },
      imagePath: 'assets/images/ind_vs_nep_football.jpg',
      isLive: false,
    ),
    Match(
      id: 'f4',
      team1: 'Chennaiyin FC',
      team2: 'FC Goa',
      dateTime: now.add(const Duration(days: 3, hours: 6, minutes: 30)),
      venue: 'Jawaharlal Nehru Stadium, Chennai',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'Tamil Nadu',
      ticketPrices: {
        'VIP': 2800.0,
        'Premium': 1800.0,
        'Regular': 900.0,
      },
      imagePath: 'assets/images/cfc_vs_fcg.jpg',
      isLive: false,
    ),
    Match(
      id: 'f5',
      team1: 'Hyderabad FC',
      team2: 'Jamshedpur FC',
      dateTime: now.add(const Duration(days: 7, hours: 7)),
      venue: 'G.M.C. Balayogi Athletic Stadium, Hyderabad',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'Telangana',
      ticketPrices: {
        'VIP': 2600.0,
        'Premium': 1700.0,
        'Regular': 850.0,
      },
      imagePath: 'assets/images/hfc_vs_jfc.jpg',
      isLive: false,
    ),
    Match(
      id: 'f6',
      team1: 'NorthEast United FC',
      team2: 'Odisha FC',
      dateTime: now.add(const Duration(days: 5, hours: 6, minutes: 30)),
      venue: 'Indira Gandhi Athletic Stadium, Guwahati',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'Assam',
      ticketPrices: {
        'VIP': 2400.0,
        'Premium': 1500.0,
        'Regular': 750.0,
      },
      imagePath: 'assets/images/neufc_vs_ofc.jpg',
      isLive: false,
    ),
    // New Football Match in West Bengal
    Match(
      id: 'f7',
      team1: 'Mohun Bagan Super Giant',
      team2: 'East Bengal FC',
      dateTime: now.add(const Duration(days: 9, hours: 6)),
      venue: 'Salt Lake Stadium, Kolkata',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 3800.0,
        'Premium': 2500.0,
        'Regular': 1200.0,
      },
      imagePath: 'assets/images/mb_vs_eb.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'f8',
      team1: 'Mohammedan SC',
      team2: 'United SC',
      dateTime: now.add(const Duration(days: 14, hours: 5, minutes: 30)),
      venue: 'Kishore Bharati Krirangan, Kolkata',
      sportType: SportType.football,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 2200.0,
        'Premium': 1400.0,
        'Regular': 700.0,
      },
      imagePath: 'assets/images/msc_vs_usc.jpg',
      isLive: false,
    ),
    
    // HOCKEY MATCHES
    Match(
      id: 'h1',
      team1: 'India',
      team2: 'Pakistan',
      dateTime: now.add(const Duration(days: 7, hours: 4)),
      venue: 'Major Dhyan Chand Stadium, Delhi',
      sportType: SportType.hockey,
      category: MatchCategory.international,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 4000.0,
        'Premium': 2500.0,
        'Regular': 1200.0,
      },
      imagePath: 'assets/images/ind_vs_pak_hockey.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'h2',
      team1: 'Punjab Warriors',
      team2: 'Delhi Waveriders',
      dateTime: now.add(const Duration(days: 5, hours: 5)),
      venue: 'Surjit Hockey Stadium, Jalandhar',
      sportType: SportType.hockey,
      category: MatchCategory.league,
      location: 'Punjab',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/pw_vs_dw_hockey.jpg',
      isLive: false,
    ),
    Match(
      id: 'h3',
      team1: 'India',
      team2: 'Australia',
      dateTime: now.add(const Duration(days: 12, hours: 3, minutes: 30)),
      venue: 'Kalinga Stadium, Bhubaneswar',
      sportType: SportType.hockey,
      category: MatchCategory.international,
      location: 'Odisha',
      ticketPrices: {
        'VIP': 3500.0,
        'Premium': 2200.0,
        'Regular': 1100.0,
      },
      imagePath: 'assets/images/ind_vs_aus_hockey.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'h4',
      team1: 'Uttar Pradesh Wizards',
      team2: 'Ranchi Rays',
      dateTime: now.add(const Duration(days: 9, hours: 4, minutes: 30)),
      venue: 'Dhyan Chand Sports College, Lucknow',
      sportType: SportType.hockey,
      category: MatchCategory.league,
      location: 'Uttar Pradesh',
      ticketPrices: {
        'VIP': 1800.0,
        'Premium': 1100.0,
        'Regular': 550.0,
      },
      imagePath: 'assets/images/upw_vs_rr_hockey.jpg',
      isLive: false,
    ),
    Match(
      id: 'h5',
      team1: 'India',
      team2: 'Germany',
      dateTime: now.add(const Duration(days: 15, hours: 4)),
      venue: 'Birsa Munda Hockey Stadium, Rourkela',
      sportType: SportType.hockey,
      category: MatchCategory.international,
      location: 'Odisha',
      ticketPrices: {
        'VIP': 3800.0,
        'Premium': 2400.0,
        'Regular': 1200.0,
      },
      imagePath: 'assets/images/ind_vs_ger_hockey.jpg',
      isLive: false,
    ),
    // New Hockey Match in West Bengal
    Match(
      id: 'h6',
      team1: 'Bengal Hockey Association',
      team2: 'Manipur Hockey',
      dateTime: now.add(const Duration(days: 11, hours: 3)),
      venue: 'SAI Complex, Kolkata',
      sportType: SportType.hockey,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1500.0,
        'Premium': 900.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/bha_vs_mh_hockey.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'h7',
      team1: 'Kolkata Hockey Club',
      team2: 'Chennai Hockey Club',
      dateTime: now.add(const Duration(days: 18, hours: 4, minutes: 30)),
      venue: 'Mohun Bagan Ground, Kolkata',
      sportType: SportType.hockey,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1200.0,
        'Premium': 800.0,
        'Regular': 400.0,
      },
      imagePath: 'assets/images/khc_vs_chc_hockey.jpg',
      isLive: false,
    ),
    
    // BADMINTON MATCHES - Increased number
    Match(
      id: 'b1',
      team1: 'Saina Nehwal',
      team2: 'P.V. Sindhu',
      dateTime: now.add(const Duration(days: 3, hours: 2)),
      venue: 'Gachibowli Indoor Stadium, Hyderabad',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'Telangana',
      ticketPrices: {
        'VIP': 2500.0,
        'Premium': 1500.0,
        'Regular': 800.0,
      },
      imagePath: 'assets/images/saina_vs_sindhu.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'b2',
      team1: 'Kidambi Srikanth',
      team2: 'H.S. Prannoy',
      dateTime: now.add(const Duration(days: 6, hours: 1, minutes: 30)),
      venue: 'Babu Banarasi Das Indoor Stadium, Lucknow',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'Uttar Pradesh',
      ticketPrices: {
        'VIP': 2200.0,
        'Premium': 1300.0,
        'Regular': 700.0,
      },
      imagePath: 'assets/images/srikanth_vs_prannoy.jpg',
      isLive: false,
    ),
    Match(
      id: 'b3',
      team1: 'Lakshya Sen',
      team2: 'Sameer Verma',
      dateTime: now.add(const Duration(days: 4, hours: 3)),
      venue: 'Siri Fort Sports Complex, Delhi',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/lakshya_vs_sameer.jpg',
      isLive: false,
    ),
    Match(
      id: 'b4',
      team1: 'India',
      team2: 'Malaysia',
      dateTime: now.add(const Duration(days: 11, hours: 2, minutes: 30)),
      venue: 'Indira Gandhi Indoor Stadium, Delhi',
      sportType: SportType.badminton,
      category: MatchCategory.international,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 3000.0,
        'Premium': 1800.0,
        'Regular': 900.0,
      },
      imagePath: 'assets/images/ind_vs_mal_badminton.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'b5',
      team1: 'Satwiksairaj Rankireddy/Chirag Shetty',
      team2: 'Dhruv Kapila/M.R. Arjun',
      dateTime: now.add(const Duration(days: 8, hours: 2)),
      venue: 'K.D. Jadhav Indoor Hall, Delhi',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 2300.0,
        'Premium': 1400.0,
        'Regular': 700.0,
      },
      imagePath: 'assets/images/satwik_chirag_vs_dhruv_arjun.jpg',
      isLive: false,
    ),
    // New Badminton Matches in West Bengal
    Match(
      id: 'b6',
      team1: 'Rituparna Das',
      team2: 'Ashmita Chaliha',
      dateTime: now.add(const Duration(days: 7, hours: 1)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1800.0,
        'Premium': 1100.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/rituparna_vs_ashmita.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'b7',
      team1: 'Sourabh Verma',
      team2: 'Subhankar Dey',
      dateTime: now.add(const Duration(days: 10, hours: 2, minutes: 30)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1700.0,
        'Premium': 1000.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/sourabh_vs_subhankar.jpg',
      isLive: false,
    ),
    Match(
      id: 'b8',
      team1: 'Ashwini Ponnappa/Tanisha Crasto',
      team2: 'Treesa Jolly/Gayatri Gopichand',
      dateTime: now.add(const Duration(days: 13, hours: 3)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/ashwini_tanisha_vs_treesa_gayatri.jpg',
      isLive: false,
    ),
    Match(
      id: 'b9',
      team1: 'Kiran George',
      team2: 'Mithun Manjunath',
      dateTime: now.add(const Duration(days: 5, hours: 4)),
      venue: 'DDA Badminton Hall, Delhi',
      sportType: SportType.badminton,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1500.0,
        'Premium': 900.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/kiran_vs_mithun.jpg',
      isLive: false,
    ),
    
    // BASKETBALL MATCHES - Increased number
    Match(
      id: 'bb1',
      team1: 'Chennai Slam',
      team2: 'Mumbai Challengers',
      dateTime: now.add(const Duration(days: 4, hours: 5)),
      venue: 'Jawaharlal Nehru Indoor Stadium, Chennai',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'Tamil Nadu',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/basketball_match.jpg',
      isLive: false,
    ),
    Match(
      id: 'bb2',
      team1: 'Delhi Capitals',
      team2: 'Bengaluru Beast',
      dateTime: now.add(const Duration(days: 8, hours: 6)),
      venue: 'K.D. Jadhav Indoor Hall, Delhi',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1800.0,
        'Premium': 1100.0,
        'Regular': 550.0,
      },
      imagePath: 'assets/images/dc_vs_bb_basketball.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'bb3',
      team1: 'Hyderabad Hoops',
      team2: 'Punjab Steelers',
      dateTime: now.add(const Duration(days: 5, hours: 7)),
      venue: 'GMC Balayogi Indoor Stadium, Hyderabad',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'Telangana',
      ticketPrices: {
        'VIP': 1700.0,
        'Premium': 1000.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/hh_vs_ps_basketball.jpg',
      isLive: false,
    ),
    Match(
      id: 'bb4',
      team1: 'Kochi Tigers',
      team2: 'Pune Panthers',
      dateTime: now.add(const Duration(days: 7, hours: 5, minutes: 30)),
      venue: 'Rajiv Gandhi Indoor Stadium, Kochi',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'Kerala',
      ticketPrices: {
        'VIP': 1900.0,
        'Premium': 1100.0,
        'Regular': 550.0,
      },
      imagePath: 'assets/images/kt_vs_pp_basketball.jpg',
      isLive: false,
    ),
    Match(
      id: 'bb5',
      team1: 'India',
      team2: 'Philippines',
      dateTime: now.add(const Duration(days: 14, hours: 4)),
      venue: 'Indira Gandhi Indoor Stadium, Delhi',
      sportType: SportType.basketball,
      category: MatchCategory.international,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 2500.0,
        'Premium': 1500.0,
        'Regular': 800.0,
      },
      imagePath: 'assets/images/ind_vs_phi_basketball.jpg',
      isLive: false,
    ),
    // New Basketball Matches in West Bengal
    Match(
      id: 'bb6',
      team1: 'Kolkata Thunders',
      team2: 'Siliguri Snipers',
      dateTime: now.add(const Duration(days: 9, hours: 6)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1800.0,
        'Premium': 1100.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/kt_vs_ss_basketball.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'bb7',
      team1: 'Durgapur Dunkers',
      team2: 'Howrah Hoopers',
      dateTime: now.add(const Duration(days: 12, hours: 5, minutes: 30)),
      venue: 'Vivekananda Yuba Bharati Krirangan, Kolkata',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1600.0,
        'Premium': 900.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/dd_vs_hh_basketball.jpg',
      isLive: false,
    ),
    Match(
      id: 'bb8',
      team1: 'West Bengal',
      team2: 'Tamil Nadu',
      dateTime: now.add(const Duration(days: 15, hours: 4)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.basketball,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/wb_vs_tn_basketball.jpg',
      isLive: false,
    ),
    Match(
      id: 'bb9',
      team1: 'Jaipur Giants',
      team2: 'Lucknow Legends',
      dateTime: now.add(const Duration(days: 6, hours: 7)),
      venue: 'SMS Indoor Stadium, Jaipur',
      sportType: SportType.basketball,
      category: MatchCategory.league,
      location: 'Rajasthan',
      ticketPrices: {
        'VIP': 1700.0,
        'Premium': 1000.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/jg_vs_ll_basketball.jpg',
      isLive: false,
    ),
    
    // TABLE TENNIS MATCHES - Increased number
    Match(
      id: 'tt1',
      team1: 'Sharath Kamal',
      team2: 'G. Sathiyan',
      dateTime: now.add(const Duration(days: 6, hours: 1)),
      venue: 'Indira Gandhi Indoor Stadium, Delhi',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1500.0,
        'Premium': 1000.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/tt_match.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'tt2',
      team1: 'Manika Batra',
      team2: 'Archana Kamath',
      dateTime: now.add(const Duration(days: 7, hours: 2)),
      venue: 'Thyagaraj Sports Complex, Delhi',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1400.0,
        'Premium': 900.0,
        'Regular': 450.0,
      },
      imagePath: 'assets/images/manika_vs_archana.jpg',
      isLive: false,
    ),
    Match(
      id: 'tt3',
      team1: 'India',
      team2: 'Japan',
      dateTime: now.add(const Duration(days: 14, hours: 3)),
      venue: 'Jawaharlal Nehru Indoor Stadium, Chennai',
      sportType: SportType.tableTennis,
      category: MatchCategory.international,
      location: 'Tamil Nadu',
      ticketPrices: {
        'VIP': 2000.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/ind_vs_jpn_tt.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'tt4',
      team1: 'Harmeet Desai',
      team2: 'Anthony Amalraj',
      dateTime: now.add(const Duration(days: 9, hours: 1, minutes: 30)),
      venue: 'Balewadi Sports Complex, Pune',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'Maharashtra',
      ticketPrices: {
        'VIP': 1300.0,
        'Premium': 800.0,
        'Regular': 400.0,
      },
      imagePath: 'assets/images/harmeet_vs_amalraj.jpg',
      isLive: false,
    ),
    // New Table Tennis Matches in West Bengal
    Match(
      id: 'tt5',
      team1: 'Sutirtha Mukherjee',
      team2: 'Reeth Rishya',
      dateTime: now.add(const Duration(days: 8, hours: 2)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1200.0,
        'Premium': 800.0,
        'Regular': 400.0,
      },
      imagePath: 'assets/images/sutirtha_vs_reeth.jpg',
      isLive: false,
      isFeatured: true,
    ),
    Match(
      id: 'tt6',
      team1: 'Manav Thakkar',
      team2: 'Sanil Shetty',
      dateTime: now.add(const Duration(days: 11, hours: 3)),
      venue: 'Khudiram Anushilan Kendra, Kolkata',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1300.0,
        'Premium': 800.0,
        'Regular': 400.0,
      },
      imagePath: 'assets/images/manav_vs_sanil.jpg',
      isLive: false,
    ),
    Match(
      id: 'tt7',
      team1: 'West Bengal',
      team2: 'Maharashtra',
      dateTime: now.add(const Duration(days: 16, hours: 2, minutes: 30)),
      venue: 'Netaji Indoor Stadium, Kolkata',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'West Bengal',
      ticketPrices: {
        'VIP': 1500.0,
        'Premium': 900.0,
        'Regular': 500.0,
      },
      imagePath: 'assets/images/wb_vs_mh_tt.jpg',
      isLive: false,
    ),
    Match(
      id: 'tt8',
      team1: 'Ayhika Mukherjee',
      team2: 'Madhurika Patkar',
      dateTime: now.add(const Duration(days: 10, hours: 4)),
      venue: 'Thyagaraj Sports Complex, Delhi',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1200.0,
        'Premium': 700.0,
        'Regular': 400.0,
      },
      imagePath: 'assets/images/ayhika_vs_madhurika.jpg',
      isLive: false,
    ),
    Match(
      id: 'tt9',
      team1: 'Sathiyan Gnanasekaran/Manika Batra',
      team2: 'Sharath Kamal/Sreeja Akula',
      dateTime: now.add(const Duration(days: 13, hours: 2)),
      venue: 'Indira Gandhi Indoor Stadium, Delhi',
      sportType: SportType.tableTennis,
      category: MatchCategory.national,
      location: 'Delhi',
      ticketPrices: {
        'VIP': 1800.0,
        'Premium': 1200.0,
        'Regular': 600.0,
      },
      imagePath: 'assets/images/sathiyan_manika_vs_sharath_sreeja.jpg',
      isLive: false,
      isFeatured: true,
    ),
  ];
}

